# This file is for Shopify employees development environment.
# If you are an external contributor you don't have to bother with it.
name: ci-queue

up:
- ruby
- bundler
- redis

commands:
  test: REDIS_URL=${REDIS_URL} bundle exec rake test TEST_FILES="$*"
