name: Tests

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Ruby tests
        run: |
          bin/before-install
          bin/test
        env:
          SUITE: ruby
          REDIS_HOST: localhost

  python-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [ '3.7', '3.8', '3.9', '3.10', '3.11' ]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get -qq update
          sudo apt-get install -y python${{ matrix.python }} python${{ matrix.python }}-distutils python${{ matrix.python }}-venv
      - name: Run Python tests
        run: |
          python3 -v
          python${{ matrix.python }} -m venv python/myenv
          source python/myenv/bin/activate
          python3 -v
          python3 -m pip install autopep8
          bin/before-install
          bin/test
        env:
          SUITE: python
          PYTHON_VERSION: ${{ matrix.python }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
